// Copyright (c) 2026 Thomas Klietsch, all rights reserved.
//
// Licensed under the GNU Lesser General Public License, version 3.0 or later
//
// This program is free software: you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public License
// as published by the Free Software Foundation, either version 3 of
// the License, or ( at your option ) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General
// Public License along with this program.If not, see < https://www.gnu.org/licenses/>. 

#pragma once

#include <cstdint>
#include <memory>
#include <vector>

#include "./../mathematics/double3.hpp"

// Data used by half-edge structure
namespace Mesh::Data {

	// Forward declaration, due to interdependencies
	struct Edge;
	struct Polygon;

	// Texture mapping coordinate
	struct Texture {

		Double3 location;

		Texture(
			Double3 const& location
		)
			: location( location )
		{};

	};

	struct Vertex {

		// Mandatory
		Double3 location;

		// Optional vertex normal, used for smooth shading.
		// Loaded from file if available, and (re)calculated during export.
		Double3 normal{ Double3::Zero };

		// Setting this to true, will treat the vertex as a boundary.
		bool f_static{ false };

		Vertex(
			Double3 const& location,
			bool const f_static = false
		)
			: location( location )
			, f_static( f_static )
		{};

		// True if the vertex is a boundary
		bool is_boundary() const { return f_static; };

	};

	struct Edge {

		// Mandatory data
		std::shared_ptr<Mesh::Data::Vertex> vertex;

		// Generated by HalfEdge::add_polygon
		std::shared_ptr<Mesh::Data::Polygon> polygon{ nullptr };

		// Optional texture coordinate
		std::shared_ptr<Mesh::Data::Texture> texture{ nullptr };

		// Setting this to true, will treat the edge as a boundary.
		// For instance for edges that are creases, or hard edges.
		// Edges will still be split if needed.
		bool f_static{ false };

		// Generated by Polygon(...) constructor
		std::shared_ptr<Mesh::Data::Edge> next{ nullptr };

		// Generated by Polygon(...) constructor
		std::shared_ptr<Mesh::Data::Edge> previous{ nullptr };

		// Generated by HalfEdge::connect_shared_edges
		std::shared_ptr<Mesh::Data::Edge> twin{ nullptr };

		// Create edge from vertex
		// Optional:
		//   f_static : true if edge is a crease/hard edge/e.t.c.
		//   texture : UV(W) texture coordinate
		//   polygon : if polygon (smart pointer) id is known
		Edge(
			std::shared_ptr<Mesh::Data::Vertex> const& p_vertex,
			bool const a_static = false,
			std::shared_ptr<Mesh::Data::Texture> const& p_texture = nullptr,
			std::shared_ptr<Mesh::Data::Polygon> const& p_polygon = nullptr
		)
			: vertex( p_vertex )
			, polygon( p_polygon )
			, texture( p_texture )
			, f_static( a_static )
		{
			vertex->f_static = a_static;
		};

		~Edge() {};

		// Angle in radiance, between this edge and previous
		std::double_t angle() const {
			Double3 const edge1 = ( next->vertex->location - vertex->location ).normalise();
			Double3 const edge2 = ( previous->vertex->location - vertex->location ).normalise();
			return std::acos( edge1.dot( edge2 ) );
		};

		// True if the edge is a boundary (no twin edge),
		// or is marked static
		bool is_boundary() const { return f_static | ( twin == nullptr ); };

		// Clears all data, e.i. set all smart pointers to nullptr
		void release() {
			// Disconnect twin edge pointing to this edge
			if ( twin != nullptr )
				twin->twin = nullptr;

			// Clear all
			twin = nullptr;
			vertex = nullptr;
			polygon = nullptr;
			texture = nullptr;
			next = nullptr;
			previous = nullptr;
		};

	};

	struct Polygon {

		// Mandatory data, closed edge loop
		std::vector<std::shared_ptr<Mesh::Data::Edge>> edge{};

		// Optional material
		std::uint32_t material_index{ 0 };

		// If true, the polygon has smooth shading
		bool f_smooth{ false };

		Polygon() {};

		Polygon(
			std::vector< std::shared_ptr<Mesh::Data::Edge> > const& p_edge,
			std::uint32_t const material_index,
			bool const f_smooth
		)
			: material_index( material_index )
			, f_smooth( f_smooth )
		{
			std::size_t const n_edge = p_edge.size();

			// Check if valid polygon size will be created
			if ( n_edge < 3 )
				return;

			// Check that vertices are valid
			for ( auto& e : p_edge )
				if ( e->vertex == nullptr )
					return;

			// Copy edges to polygon
			edge = p_edge;

			// Set next and previous edge in edge loop
			for ( std::size_t i{ 0 };i < n_edge; ++i ) {
				edge[i]->next = edge[( i + 1 ) % n_edge];
				// The result of (a mod n), is unaffected by addition of n's to a,
				// therefore underflow is avoided below.
				edge[i]->previous = edge[( i + n_edge - 1 ) % n_edge];
			}

			// Process edges for boundary state,
			// if true update connected vertices
			for ( auto& e : edge )
				if ( e->is_boundary() ) {
					e->vertex->f_static = true;
					e->next->vertex->f_static = true;
				}

			// TODO generate twin edges?
		};

		~Polygon() {};

		// Calculate the centre (average) of polygon vertices.
		Double3 centre() const {
			Double3 sum{ Double3::Zero };
			for ( auto v : edge )
				sum += v->vertex->location;
			return sum / edge.size();
		};

		// Area of polygon
		std::double_t area() const {
			if ( edge.size() == 3 ) {
				Double3 const& v0 = edge[0]->vertex->location;
				Double3 const& v1 = edge[1]->vertex->location;
				Double3 const& v2 = edge[2]->vertex->location;
				// Area of triangle is half of parallelogram
				return ( ( v1 - v0 ).cross( v2 - v0 ) ).magnitude() * .5;
			}

			std::double_t sum{ 0. };
			Double3 const v2 = centre();
			for ( auto& e : edge ) {
				Double3 const& v0 = e->vertex->location;
				Double3 const& v1 = e->next->vertex->location;
				// Area of a parallelogram is the length of the edges cross product
				sum += ( ( v1 - v0 ).cross( v2 - v0 ) ).magnitude();
			}
			// Area of triangle is half of parallelogram
			return sum * .5;
		};

		// Calculated the normalised normal for a polygon.
		Double3 unit_normal() {
			if ( edge.size() == 3 ) {
				Double3 const& v0 = edge[0]->vertex->location;
				Double3 const& v1 = edge[1]->vertex->location;
				Double3 const& v2 = edge[2]->vertex->location;
				return ( ( v1 - v0 ).cross( v2 - v0 ) ).normalise();
			}

			Double3 const v2 = centre();
			Double3 result{ Double3::Zero };

			for ( auto const& e : edge ) {
				Double3 const& v0 = e->vertex->location;
				Double3 const& v1 = e->next->vertex->location;
				result += ( ( v1 - v0 ).cross( v2 - v0 ) ).normalise();
			}
			return result.normalise();
		};

		// Calculated the (area) weighted normal for a polygon.
		Double3 weighted_normal() {
			if ( edge.size() == 3 ) {
				Double3 const& v0 = edge[0]->vertex->location;
				Double3 const& v1 = edge[1]->vertex->location;
				Double3 const& v2 = edge[2]->vertex->location;
				return ( ( v1 - v0 ).cross( v2 - v0 ) ) * 0.5;
			}

			Double3 const v2 = centre();
			Double3 result{ Double3::Zero };

			// Full calculation of weighted normal
			// = ( Triangle fan sum ).normalise * area
			// Note:
			//   area = (Triangle fan sum).magnitude() * 0.5
			//   normalise = 1 / (Triangle fan sum).magnitude()
			// = ( Triangle fan sum ) * .5
			for ( auto const& e : edge ) {
				Double3 const& v0 = e->vertex->location;
				Double3 const& v1 = e->next->vertex->location;
				result += ( v1 - v0 ).cross( v2 - v0 );
			}
			return result * .5;
		};

		// Return true if all edges have a texture defined
		bool is_textured() const {
			for ( auto& e : edge )
				if ( e->texture == nullptr )
					return false;

			return true;
		};

		// Clears all data, e.i. set all smart pointers to nullptr,
		// removes edge data.
		void release() {
			// Process edges
			for ( auto& e : edge ) {
				e->release();
				e = nullptr;
			}

			edge.clear();
			edge.shrink_to_fit();
		};

	};

};
